### ISSUE TITLE
Run on mac

### ISSUE THREAD

**Issue by tavcas** [clibequilibrium/EquilibriumEngine-CSharp#1]
Is it possible to run on Mac? I cloned the project and followed the guide but I get this error when I try to run it
```
MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  shared -> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/shared/bin/Debug/net7.0/shared.dll
/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/Arch.System.SourceGenerator/Arch.System.SourceGenerator.QueryGenerator/ImGuiBgfxSdlSystem.g.cs(10,30): error CS0115: 'ImGuiBgfxSdlSystem.Update(in float)': no suitable method found to override [/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/equilibrium.csproj]
/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/Arch.System.SourceGenerator/Arch.System.SourceGenerator.QueryGenerator/BgfxSystem.g.cs(10,30): error CS0115: 'BgfxSystem.Update(in float)': no suitable method found to override [/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/equilibrium.csproj]
/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/Arch.System.SourceGenerator/Arch.System.SourceGenerator.QueryGenerator/SdlSystem.g.cs(10,30): error CS0115: 'SdlSystem.Update(in float)': no suitable method found to override [/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/equilibrium.csproj]
CSC : warning CS8785: Generator 'QueryGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'Collection was modified; enumeration operation may not execute.'. [/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj]
  engine -> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/bin/Debug/net7.0/engine.dll
  Building plugin equilibrium
  shared -> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/bin/Debug/net7.0/equilibrium/shared.dll
  equilibrium -> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/bin/Debug/net7.0/equilibrium/equilibrium.dll
/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018: The "ShaderCompilerTask" task failed unexpectedly.
/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018: System.InvalidOperationException: Cannot start process because a file name has not been provided.
/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018:    at System.Diagnostics.Process.Start()
/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018:    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018:    at ShaderCompilerTask.Execute() in /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/shared/ShaderCompilerTask.cs:line 112
/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)

Build FAILED.

CSC : warning CS8785: Generator 'QueryGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'Collection was modified; enumeration operation may not execute.'. [/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj]
/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/Arch.System.SourceGenerator/Arch.System.SourceGenerator.QueryGenerator/ImGuiBgfxSdlSystem.g.cs(10,30): error CS0115: 'ImGuiBgfxSdlSystem.Update(in float)': no suitable method found to override [/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/equilibrium.csproj]
/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/Arch.System.SourceGenerator/Arch.System.SourceGenerator.QueryGenerator/BgfxSystem.g.cs(10,30): error CS0115: 'BgfxSystem.Update(in float)': no suitable method found to override [/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/equilibrium.csproj]
/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/Arch.System.SourceGenerator/Arch.System.SourceGenerator.QueryGenerator/SdlSystem.g.cs(10,30): error CS0115: 'SdlSystem.Update(in float)': no suitable method found to override [/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/equilibrium.csproj]
/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018: The "ShaderCompilerTask" task failed unexpectedly.
/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018: System.InvalidOperationException: Cannot start process because a file name has not been provided.
/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018:    at System.Diagnostics.Process.Start()
/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018:    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018:    at ShaderCompilerTask.Execute() in /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/shared/ShaderCompilerTask.cs:line 112
/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
    1 Warning(s)
    4 Error(s)

Time Elapsed 00:00:03.10
```

**Comment by clibequilibrium** [comment]
> Is it possible to run on Mac? I cloned the project and followed the guide but I get this error when I try to run it
> 
> ```
> MSBuild version 17.8.3+195e7f5a3 for .NET
>   Determining projects to restore...
>   All projects are up-to-date for restore.
>   shared -> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/shared/bin/Debug/net7.0/shared.dll
> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/Arch.System.SourceGenerator/Arch.System.SourceGenerator.QueryGenerator/ImGuiBgfxSdlSystem.g.cs(10,30): error CS0115: 'ImGuiBgfxSdlSystem.Update(in float)': no suitable method found to override [/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/equilibrium.csproj]
> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/Arch.System.SourceGenerator/Arch.System.SourceGenerator.QueryGenerator/BgfxSystem.g.cs(10,30): error CS0115: 'BgfxSystem.Update(in float)': no suitable method found to override [/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/equilibrium.csproj]
> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/Arch.System.SourceGenerator/Arch.System.SourceGenerator.QueryGenerator/SdlSystem.g.cs(10,30): error CS0115: 'SdlSystem.Update(in float)': no suitable method found to override [/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/equilibrium.csproj]
> CSC : warning CS8785: Generator 'QueryGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'Collection was modified; enumeration operation may not execute.'. [/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj]
>   engine -> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/bin/Debug/net7.0/engine.dll
>   Building plugin equilibrium
>   shared -> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/bin/Debug/net7.0/equilibrium/shared.dll
>   equilibrium -> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/bin/Debug/net7.0/equilibrium/equilibrium.dll
> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018: The "ShaderCompilerTask" task failed unexpectedly.
> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018: System.InvalidOperationException: Cannot start process because a file name has not been provided.
> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018:    at System.Diagnostics.Process.Start()
> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018:    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018:    at ShaderCompilerTask.Execute() in /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/shared/ShaderCompilerTask.cs:line 112
> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
> 
> Build FAILED.
> 
> CSC : warning CS8785: Generator 'QueryGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'Collection was modified; enumeration operation may not execute.'. [/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj]
> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/Arch.System.SourceGenerator/Arch.System.SourceGenerator.QueryGenerator/ImGuiBgfxSdlSystem.g.cs(10,30): error CS0115: 'ImGuiBgfxSdlSystem.Update(in float)': no suitable method found to override [/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/equilibrium.csproj]
> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/Arch.System.SourceGenerator/Arch.System.SourceGenerator.QueryGenerator/BgfxSystem.g.cs(10,30): error CS0115: 'BgfxSystem.Update(in float)': no suitable method found to override [/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/equilibrium.csproj]
> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/Arch.System.SourceGenerator/Arch.System.SourceGenerator.QueryGenerator/SdlSystem.g.cs(10,30): error CS0115: 'SdlSystem.Update(in float)': no suitable method found to override [/Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/equilibrium/equilibrium.csproj]
> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018: The "ShaderCompilerTask" task failed unexpectedly.
> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018: System.InvalidOperationException: Cannot start process because a file name has not been provided.
> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018:    at System.Diagnostics.Process.Start()
> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018:    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018:    at ShaderCompilerTask.Execute() in /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/shared/ShaderCompilerTask.cs:line 112
> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
> /Users/frontendguru/Documents/GitHub/Equilibrium-Engine/EquilibriumEngine-CSharp/engine/engine.csproj(54,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
>     1 Warning(s)
>     4 Error(s)
> 
> Time Elapsed 00:00:03.10
> ```

Hi, I haven't tested it on Mac, it should only work on Windows. 

To get it working you would need native libraries of bgfx complied for mac toolchain as well as SDL. The error you have provided is related to Arch source code generator. Do you use VSCode or Visual Studio?

**Comment by tavcas** [comment]
I use vscode, I will look for it to see if I can find a way to build them for mac

**Comment by clibequilibrium** [comment]
> I use vscode, I will look for it to see if I can find a way to build them for mac

I can also try to help you out , which Mac OS version are you on?
